name: Binaries
on:
  workflow_call:
jobs:
  Archive:
    name: ${{ matrix.config.name }} ${{ matrix.binaries }}
    runs-on: ${{ matrix.config.os }}
    env:
      COMPILER: ${{ matrix.config.compiler }}
      COMP: ${{ matrix.config.comp }}
      EXT: ${{ matrix.config.ext }}
      OS: ${{ matrix.config.os }}
      BINARY: ${{ matrix.binaries }}
    strategy:
      matrix:
        config:
          - {
              name: "Ubuntu 20.04 GCC",
              os: ubuntu-20.04,
              compiler: g++,
              comp: gcc,
              shell: 'bash {0}'
            }
          - {
              name: "MacOS 12 Apple Clang",
              os: macos-12,
              compiler: clang++,
              comp: clang,
              shell: 'bash {0}'
            }
          - {
              name: "Windows 2022 GCC",
              os: windows-2022,
              compiler: g++,
              comp: MINGW,
              msys_sys: 'mingw64',
              msys_env: 'x86_64-gcc',
              shell: 'msys2 {0}',
              ext: .exe
            }
        binaries:
          - x86-64
          - x86-64-modern
          - x86-64-avx2
        exclude:
          - binaries: x86-64-avx2
            config: {os: macos-12}
    defaults:
      run:
        working-directory: src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Download required linux packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update

      - name: Setup msys and install required packages
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.config.msys_sys}}
          install: mingw-w64-${{matrix.config.msys_env}} make git expect

      - name: Switch to gcc-10 on linux
        if: runner.os == 'Linux'
        run: |
          sudo apt install gcc-10 g++-10
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 100 --slave /usr/bin/g++ g++ /usr/bin/g++-10 --slave /usr/bin/gcov gcov /usr/bin/gcov-10
          sudo update-alternatives --set gcc /usr/bin/gcc-10

      - name: Extract the commit sha
        run: |
          git rev-parse --short "$GITHUB_SHA" > sha && echo "git_sha=$(cat sha)" >> $GITHUB_ENV && echo "Git sha:" $(cat sha)

      - name: Create binary folder
        run: |
          mkdir ../binaries

      # Compile profile guided builds

      - name: Compile ${{ matrix.binaries }} build
        run: |
          make clean
          make build=$BINARY sha=$git_sha COMP=$COMP
          strip ./smallbrain-$BINARY$EXT
          mv ./smallbrain-$BINARY$EXT ../smallbrain-$OS-$BINARY$EXT

      - name: Find and remove empty files
        run: rm -f *.o *.nnue sha
        shell: bash

      - name: Archive binaries
        uses: actions/upload-artifact@v3
        with:
          name: smallbrain-${{ matrix.config.os }}-${{ matrix.binaries }}
          path: |
            src
            README.md
            LICENSE
            smallbrain-${{ matrix.config.os }}-${{ matrix.binaries }}${{ matrix.config.ext }}