name: Test bench
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Windows 2022 Mingw-w64 GCC x86_64",
            os: windows-2022,
            compiler: g++,
            comp: mingw,
            msys_sys: 'mingw64',
            msys_env: 'x86_64-gcc',
            shell: 'msys2 {0}',
            ext: ".exe"
          }
        - {
            name: "Ubuntu 20.04 Clang",
            os: ubuntu-20.04,
            compiler: clang++,
            comp: clang,
            shell: 'bash {0}',
            ext: ""
          }
    defaults:
      run:
        working-directory: ./src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies on windows
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.config.msys_sys}}
          install: mingw-w64-${{matrix.config.msys_env}} make git expect

      - name: Download required linux packages
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install expect valgrind g++-multilib qemu-user

      - name: make
        run: make

      - name: bench
        run: ./smallbrain* bench

      - name: Perft and valgrind
        if: runner.os == 'Linux'
        run: |
          ./smallbrain* perft
          valgrind ./smallbrain* bench
