name: Test bench
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config: 
        - {
            name: "Ubuntu 20.04 GCC",
            os: ubuntu-20.04,
            compiler: g++,
            comp: gcc,
            shell: 'bash {0}'
          }
    defaults:
      run:
        working-directory: ./src
        shell: ${{ matrix.config.shell }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Download required linux packages
        run: |
          sudo apt-get install g++
          sudo apt update
          wget ftp://sourceware.org/pub/valgrind/valgrind-3.19.0.tar.bz2
          tar xvf valgrind-3.19.0.tar.bz2
          cd valgrind-3.19.0
          ./configure
          make
          sudo make install
          valgrind --version

      - name: make
        run: make

      - name: bench
        run: ./smallbrain* bench

      - name: Perft and valgrind
        run: |
          ./smallbrain* perft
          valgrind ./smallbrain* bench
